channels:
  - conda-forge
  - nvidia
dependencies:
  - pip
  - nltk 
  - gensim 
  - bokeh
  - jupyter
  - scikit-learn
  - matplotlib
  - seaborn
  - cuda=12.4
  - bitsandbytes
  - pip:
    - -r requirements.txt
